<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnimalsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get category IDs
        $categories = DB::table('categories')->select('id', 'name')->get();
        $categoryIds = [];
        foreach ($categories as $category) {
            $categoryIds[$category->name] = $category->id;
        }

        $animals = [
            // Invertebrates
            [
                'name' => 'Giant Pacific Octopus',
                'short_name' => 'Octopus',
                'size' => 'Up to 16 feet arm span',
                'habitat' => 'Marine',
                'diet' => 'Carnivore',
                'region' => 'North Pacific Ocean',
                'lifespan' => '3-5 years',
                'has_legs' => false,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Invertebrates'],
                'description' => 'The Giant Pacific Octopus is one of the most intelligent invertebrates, known for its problem-solving abilities and color-changing camouflage. They can use tools, solve puzzles, and have been known to escape from aquariums.',
                'image_url' => 'octopus.jpg',
                'initial_hint' => 'I can change my skin color and escape from tanks!',
            ],
            [
                'name' => 'Emperor Butterfly',
                'short_name' => 'Butterfly',
                'size' => '4-inch wingspan',
                'habitat' => 'Tropical forests',
                'diet' => 'Nectar',
                'region' => 'South America',
                'lifespan' => '6-8 months',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => false,
                'can_fly' => true,
                'is_carnivore' => false,
                'category_id' => $categoryIds['Invertebrates'],
                'description' => 'These magnificent butterflies are known for their striking blue iridescent wings and complex social behaviors. They play a crucial role in pollination within their ecosystem.',
                'image_url' => 'butterfly.jpg',
                'initial_hint' => 'My shimmering blue wings help pollinate the forest!',
            ],
            [
                'name' => 'Giant Australian Cuttlefish',
                'short_name' => 'Cuttlefish',
                'size' => 'Up to 20 inches',
                'habitat' => 'Marine reefs',
                'diet' => 'Carnivore',
                'region' => 'Southern Australian waters',
                'lifespan' => '2-4 years',
                'has_legs' => false,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Invertebrates'],
                'description' => 'Masters of disguise, these cephalopods can instantly change their color and texture to match their surroundings. Males put on spectacular displays during mating season.',
                'image_url' => 'cuttlefish.jpg',
                'initial_hint' => 'I can change both my color AND texture to hide!',
            ],
            [
                'name' => 'Goliath Bird-Eating Spider',
                'short_name' => 'Spider',
                'size' => '11-inch leg span',
                'habitat' => 'Rainforest floor',
                'diet' => 'Carnivore',
                'region' => 'South America',
                'lifespan' => '15-25 years',
                'has_legs' => true,
                'has_fur' => true,
                'can_swim' => false,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Invertebrates'],
                'description' => 'The largest spider by mass, this tarantula species can consume small birds, though it primarily feeds on insects and small vertebrates. Despite its intimidating size, it rarely poses a threat to humans.',
                'image_url' => 'spider.jpg',
                'initial_hint' => "I'm the heaviest spider in the world!",
            ],
            [
                'name' => 'Giant Clam',
                'short_name' => 'Clam',
                'size' => 'Up to 4 feet wide',
                'habitat' => 'Coral reefs',
                'diet' => 'Filter feeder',
                'region' => 'Indo-Pacific',
                'lifespan' => 'Over 100 years',
                'has_legs' => false,
                'has_fur' => false,
                'can_swim' => false,
                'can_fly' => false,
                'is_carnivore' => false,
                'category_id' => $categoryIds['Invertebrates'],
                'description' => 'These massive bivalves can weigh up to 500 pounds. They form symbiotic relationships with algae and are crucial to reef ecosystems. Their shells can be brightly colored due to the presence of photosynthetic algae.',
                'image_url' => 'clam.jpg',
                'initial_hint' => 'I can live for over a century in my colorful shell!',
            ],
            // fish
            [
                'name' => 'Great White Shark',
                'short_name' => 'Shark',
                'size' => 'Up to 20 feet',
                'habitat' => 'Marine',
                'diet' => 'Carnivore',
                'region' => 'Global oceans',
                'lifespan' => '70+ years',
                'has_legs' => false,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Fish'],
                'description' => 'The largest predatory fish, great whites are known for their size and powerful jaws. Despite their fearsome reputation, they rarely attack humans and are crucial for ocean ecosystem balance.',
                'image_url' => 'shark.jpg',
                'initial_hint' => "I'm the biggest hunting fish in the ocean!",
            ],
            [
                'name' => 'Electric Eel',
                'short_name' => 'Eel',
                'size' => 'Up to 8 feet',
                'habitat' => 'Freshwater',
                'diet' => 'Carnivore',
                'region' => 'South America',
                'lifespan' => '15-20 years',
                'has_legs' => false,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Fish'],
                'description' => 'Despite their name, they are not true eels but belong to the knifefish family. They can generate electric charges up to 860 volts to stun prey and defend themselves.',
                'image_url' => 'eel.jpg',
                'initial_hint' => 'I can make electricity to zap my prey!',
            ],
            [
                'name' => 'Ocean Sunfish',
                'short_name' => 'Sunfish',
                'size' => 'Up to 14 feet',
                'habitat' => 'Marine',
                'diet' => 'Omnivore',
                'region' => 'Tropical and temperate oceans',
                'lifespan' => '20-30 years',
                'has_legs' => false,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => false,
                'category_id' => $categoryIds['Fish'],
                'description' => 'The heaviest known bony fish, sunfish can weigh up to 5,000 pounds. They often bask on their sides at the surface, leading to their name. Their diet consists mainly of jellyfish.',
                'image_url' => 'sunfish.jpg',
                'initial_hint' => 'I weigh as much as a car and love to sunbathe!',
            ],
            [
                'name' => 'Seahorse',
                'short_name' => 'Seahorse',
                'size' => '0.6-14 inches',
                'habitat' => 'Marine',
                'diet' => 'Carnivore',
                'region' => 'Global tropical waters',
                'lifespan' => '1-5 years',
                'has_legs' => false,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Fish'],
                'description' => 'Unique among fish, male seahorses carry and give birth to young. They use their prehensile tails to anchor themselves and are masters of camouflage.',
                'image_url' => 'seahorse.jpg',
                'initial_hint' => 'My dad carries babies in his pouch!',
            ],
            [
                'name' => 'Flying Fish',
                'short_name' => 'Fish',
                'size' => 'Up to 18 inches',
                'habitat' => 'Marine',
                'diet' => 'Omnivore',
                'region' => 'Tropical and subtropical oceans',
                'lifespan' => '5 years',
                'has_legs' => false,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => true,
                'is_carnivore' => false,
                'category_id' => $categoryIds['Fish'],
                'description' => 'These remarkable fish can leap out of water and glide for distances up to 200 meters using their enlarged pectoral fins as wings. This ability helps them escape predators.',
                'image_url' => 'flying-fish.jpg',
                'initial_hint' => 'I can glide through the air for two football fields!',
            ],

// Amphibians
            [
                'name' => 'Chinese Giant Salamander',
                'short_name' => 'Salamander',
                'size' => 'Up to 6 feet',
                'habitat' => 'Freshwater',
                'diet' => 'Carnivore',
                'region' => 'China',
                'lifespan' => '60+ years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Amphibians'],
                'description' => 'The largest amphibian in the world, these salamanders can detect prey using special sensory nodes that run along their bodies. They are considered living fossils, having remained largely unchanged for millions of years.',
                'image_url' => 'salamander.jpg',
                'initial_hint' => "I'm as long as a grown-up, and I haven't changed in millions of years!",
            ],
            [
                'name' => 'Red-Eyed Tree Frog',
                'short_name' => 'Frog',
                'size' => '2-3 inches',
                'habitat' => 'Rainforest',
                'diet' => 'Carnivore',
                'region' => 'Central America',
                'lifespan' => '5-10 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Amphibians'],
                'description' => 'Known for their vibrant red eyes and bright green bodies, these iconic rainforest amphibians are excellent climbers. They sleep during the day with their eyes closed, blending in with leaves.',
                'image_url' => 'tree-frog.jpg',
                'initial_hint' => "I've got big, bright red eyes and can blend in with leaves to hide from danger!",
            ],
            [
                'name' => 'Fire Salamander',
                'short_name' => 'Salamander',
                'size' => '6-8 inches',
                'habitat' => 'Forest',
                'diet' => 'Carnivore',
                'region' => 'Europe',
                'lifespan' => '20-30 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Amphibians'],
                'description' => 'Their striking black and yellow coloration warns predators of their toxic skin secretions. They are one of the few salamanders that give birth to live young instead of laying eggs.',
                'image_url' => 'fire-salamander.jpg',
                'initial_hint' => "With my bright yellow spots, I’m like a warning sign you can't miss!",
            ],
            [
                'name' => 'Poison Dart Frog',
                'short_name' => 'Frog',
                'size' => '1-2 inches',
                'habitat' => 'Rainforest',
                'diet' => 'Carnivore',
                'region' => 'South America',
                'lifespan' => '3-15 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Amphibians'],
                'description' => 'Among the most toxic animals on Earth, their bright colors warn predators of their potent poison. In captivity, they become non-toxic due to their specialized wild diet.',
                'image_url' => 'dart-frog.jpg',
                'initial_hint' => "I'm tiny but mighty—my bright colors tell everyone to stay away!",
            ],
            [
                'name' => 'Axolotl',
                'short_name' => 'Axolotl',
                'size' => '8-12 inches',
                'habitat' => 'Freshwater',
                'diet' => 'Carnivore',
                'region' => 'Mexico',
                'lifespan' => '10-15 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Amphibians'],
                'description' => 'These salamanders never undergo metamorphosis, keeping their larval features throughout life. They can regenerate entire lost limbs and organs, making them valuable for scientific research.',
                'image_url' => 'axolotl.jpg',
                'initial_hint' => "I’m the salamander that never grows up—and I can regrow my arms and legs!",
            ],


// Birds
            [
                'name' => 'Wandering Albatross',
                'short_name' => 'Albatross',
                'size' => '11.5 feet wingspan',
                'habitat' => 'Marine',
                'diet' => 'Carnivore',
                'region' => 'Southern Ocean',
                'lifespan' => '50+ years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => true,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Birds'],
                'description' => 'Having the largest wingspan of any living bird, these seabirds can glide for hours without flapping their wings. They mate for life and spend most of their lives at sea, returning to land only to breed.',
                'image_url' => 'albatross.jpg',
                'initial_hint' => "I’ve got wings as wide as a bus, and I can soar over the ocean all day long!",
            ],
            [
                'name' => 'Peregrine Falcon',
                'short_name' => 'Falcon',
                'size' => '3.3-3.6 feet wingspan',
                'habitat' => 'Various',
                'diet' => 'Carnivore',
                'region' => 'Worldwide',
                'lifespan' => '15-20 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => false,
                'can_fly' => true,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Birds'],
                'description' => 'The fastest animal on Earth, reaching speeds over 240 mph during hunting dives. They are found on every continent except Antarctica and have adapted to live in cities, nesting on skyscrapers.',
                'image_url' => 'falcon.jpg',
                'initial_hint' => "I'm the fastest animal on Earth, diving faster than a race car at 240 mph!",
            ],
            [
                'name' => 'Emperor Penguin',
                'short_name' => 'Penguin',
                'size' => '4 feet tall',
                'habitat' => 'Antarctic',
                'diet' => 'Carnivore',
                'region' => 'Antarctica',
                'lifespan' => '20 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Birds'],
                'description' => 'The largest penguin species, they survive the harsh Antarctic winter by huddling together in large groups. Males incubate eggs on their feet under a flap of skin while females travel up to 50 miles to feed.',
                'image_url' => 'penguin.jpg',
                'initial_hint' => "I’m as tall as some kids and huddle with my friends to stay warm in icy Antarctica!",
            ],
            [
                'name' => 'Common Raven',
                'short_name' => 'Raven',
                'size' => '4.5 feet wingspan',
                'habitat' => 'Various',
                'diet' => 'Omnivore',
                'region' => 'Northern Hemisphere',
                'lifespan' => '10-15 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => false,
                'can_fly' => true,
                'is_carnivore' => false,
                'category_id' => $categoryIds['Birds'],
                'description' => 'Among the most intelligent of all birds, ravens can solve complex problems, use tools, and even mimic human speech. They are known to play games, create toys, and work cooperatively to find food.',
                'image_url' => 'raven.jpg',
                'initial_hint' => "I’m super smart and can even play games and mimic sounds, just like a little feathered genius!",
            ],
            [
                'name' => 'Harpy Eagle',
                'short_name' => 'Eagle',
                'size' => '6.5 feet wingspan',
                'habitat' => 'Rainforest',
                'diet' => 'Carnivore',
                'region' => 'Central and South America',
                'lifespan' => '25-35 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => false,
                'can_fly' => true,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Birds'],
                'description' => 'One of the most powerful eagles, with talons the size of grizzly bear claws. They can lift prey equal to their own body weight and are considered sacred by many indigenous peoples.',
                'image_url' => 'harpy.jpg',
                'initial_hint' => "I’m the rainforest’s mighty hunter, with claws as big as a grizzly bear’s!",
            ],
// Mammals
            [
                'name' => 'African Elephant',
                'short_name' => 'Elephant',
                'size' => 'Up to 13 feet tall',
                'habitat' => 'Savanna',
                'diet' => 'Herbivore',
                'region' => 'Africa',
                'lifespan' => '60-70 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => false,
                'category_id' => $categoryIds['Mammals'],
                'description' => 'The largest land animal, known for their intelligence, complex social structures, and remarkable memory. They play a crucial role in maintaining their ecosystem as keystone species.',
                'image_url' => 'elephant.jpg',
                'initial_hint' => "I’m as tall as a one-story house and never forget a thing!",
            ],
            [
                'name' => 'Blue Whale',
                'short_name' => 'Whale',
                'size' => 'Up to 100 feet',
                'habitat' => 'Marine',
                'diet' => 'Carnivore',
                'region' => 'Global oceans',
                'lifespan' => '80-90 years',
                'has_legs' => false,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Mammals'],
                'description' => 'The largest animal known to have ever existed, blue whales can weigh up to 200 tons. Their hearts are the size of a car, and their songs can be heard for hundreds of miles underwater.',
                'image_url' => 'whale.jpg',
                'initial_hint' => "I’m as long as two buses and my heart is the size of a car!",
            ],
            [
                'name' => 'Red Kangaroo',
                'short_name' => 'Kangaroo',
                'size' => 'Up to 6 feet tall',
                'habitat' => 'Desert and grassland',
                'diet' => 'Herbivore',
                'region' => 'Australia',
                'lifespan' => '20-25 years',
                'has_legs' => true,
                'has_fur' => true,
                'can_swim' => false,
                'can_fly' => false,
                'is_carnivore' => false,
                'category_id' => $categoryIds['Mammals'],
                'description' => 'The largest marsupial alive today, known for their powerful legs and tail. They can travel at speeds up to 35mph and their joeys develop in a pouch for several months after birth.',
                'image_url' => 'kangaroo.jpg',
                'initial_hint' => "I can hop faster than a bike at 35 mph, and I carry my baby in a pouch!",
            ],
            [
                'name' => 'Arctic Fox',
                'short_name' => 'Fox',
                'size' => '2-3 feet long',
                'habitat' => 'Tundra',
                'diet' => 'Carnivore',
                'region' => 'Arctic Circle',
                'lifespan' => '3-6 years',
                'has_legs' => true,
                'has_fur' => true,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Mammals'],
                'description' => 'Their fur changes color seasonally - white in winter and brown in summer - for perfect camouflage. They can survive temperatures as low as -50°C and their round, furry bodies help conserve heat.',
                'image_url' => 'fox.jpg',
                'initial_hint' => "I’m a master of disguise, turning white in winter and brown in summer!",
            ],
            [
                'name' => 'Orangutan',
                'short_name' => 'Orangutan',
                'size' => '4-5 feet tall',
                'habitat' => 'Rainforest',
                'diet' => 'Omnivore',
                'region' => 'Borneo and Sumatra',
                'lifespan' => '35-45 years',
                'has_legs' => true,
                'has_fur' => true,
                'can_swim' => false,
                'can_fly' => false,
                'is_carnivore' => false,
                'category_id' => $categoryIds['Mammals'],
                'description' => 'Among our closest relatives, orangutans are highly intelligent apes known for their tool use and complex cultural behaviors. They spend most of their time in trees and build nests each night for sleeping.',
                'image_url' => 'orangutan.jpg',
                'initial_hint' => "I’m a clever ape who builds a brand-new treetop nest every night!",
            ],
// Reptiles
            [
                'name' => 'Komodo Dragon',
                'short_name' => 'Dragon',
                'size' => 'Up to 10 feet long',
                'habitat' => 'Tropical savannas and forests',
                'diet' => 'Carnivore',
                'region' => 'Indonesia',
                'lifespan' => '30 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Reptiles'],
                'description' => 'The largest lizard in the world, Komodo dragons have venomous bites and can take down prey much larger than themselves. They rely on their powerful tails, claws, and incredible sense of smell to hunt.',
                'image_url' => 'komodo-dragon.jpg',
                'initial_hint' => "I’m a giant lizard with a venomous bite and a tail as strong as my legs!",
            ],
            [
                'name' => 'Green Sea Turtle',
                'short_name' => 'Turtle',
                'size' => 'Up to 5 feet long',
                'habitat' => 'Tropical and subtropical oceans',
                'diet' => 'Herbivore',
                'region' => 'Worldwide',
                'lifespan' => '80-100 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => false,
                'category_id' => $categoryIds['Reptiles'],
                'description' => 'Green sea turtles travel thousands of miles across oceans to reach nesting sites. They have a diet mostly of seagrass and algae, which gives their fat a greenish tint, hence their name!',
                'image_url' => 'green-sea-turtle.jpg',
                'initial_hint' => "I’m a long-distance swimmer who can cross oceans and live up to 100 years!",
            ],
            [
                'name' => 'King Cobra',
                'short_name' => 'Cobra',
                'size' => 'Up to 18 feet long',
                'habitat' => 'Rainforests and plains',
                'diet' => 'Carnivore',
                'region' => 'South and Southeast Asia',
                'lifespan' => '20 years',
                'has_legs' => false,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Reptiles'],
                'description' => 'The longest venomous snake in the world, king cobras can "stand up" and look a human in the eye when threatened. They are famous for their hooded necks and loud hissing sounds.',
                'image_url' => 'king-cobra.jpg',
                'initial_hint' => "I can raise a third of my body and look you in the eye!",
            ],
            [
                'name' => 'Galapagos Tortoise',
                'short_name' => 'Tortoise',
                'size' => 'Up to 5 feet long',
                'habitat' => 'Grasslands and forests',
                'diet' => 'Herbivore',
                'region' => 'Galapagos Islands',
                'lifespan' => '100-150 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => false,
                'can_fly' => false,
                'is_carnivore' => false,
                'category_id' => $categoryIds['Reptiles'],
                'description' => 'These gentle giants are the longest-living land animals, known for their slow movements and giant shells. They can go without food or water for over a year if needed.',
                'image_url' => 'galapagos-tortoise.jpg',
                'initial_hint' => "I’m a slow giant who can live over 100 years and survive without food for months!",
            ],
            [
                'name' => 'American Alligator',
                'short_name' => 'Alligator',
                'size' => 'Up to 13 feet long',
                'habitat' => 'Freshwater swamps and rivers',
                'diet' => 'Carnivore',
                'region' => 'Southeastern United States',
                'lifespan' => '35-50 years',
                'has_legs' => true,
                'has_fur' => false,
                'can_swim' => true,
                'can_fly' => false,
                'is_carnivore' => true,
                'category_id' => $categoryIds['Reptiles'],
                'description' => 'American alligators have strong jaws capable of crushing bones and a powerful tail for swimming. They are an ancient species, around since the time of the dinosaurs!',
                'image_url' => 'american-alligator.jpg',
                'initial_hint' => "I’m an ancient predator with a bite strong enough to crush bones!",
            ],

        ];

        $now = now();
        $animals = array_map(function($animal) use ($now) {
            return array_merge($animal, [
                'created_at' => $now,
                'updated_at' => $now
            ]);
        }, $animals);

        DB::table('animals')->insert($animals);
    }
}
